### ISSUE TITLE
Clean up Google Drive files

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#111]
Reminder for me.

**Comment by franciscawijaya** [comment]
Add documentation for the files in Google Drive (ie. the 8-batches and other Misc. files). There are also some files that I might need to confirm. I could then either put it in the ReadME or wiki (to be determined).

**Comment by SebastianZimmeck** [comment]
Thanks, @franciscawijaya!

Can you start with the file and directory names and make them visually more clear as, for example, in the [OptMeowt repo readme](https://github.com/privacy-tech-lab/gpc-optmeowt?tab=readme-ov-file#10-directories-in-this-repo)? That would make it a bit easier to grasp. Essentially, you have the content, but the formatting makes it a bit difficult to follow.

**Comment by franciscawijaya** [comment]
Done! I've cleaned up the formatting.

**Comment by SebastianZimmeck** [comment]
Thanks, @franciscawijaya!

I made a few smaller modifications.

Can you add descriptions of the Crawl_Data and sites_with_GPP files?

**Comment by franciscawijaya** [comment]
Got it! I've added descriptions for both Crawl_Data and sites_with_GPP.

**Comment by SebastianZimmeck** [comment]
Looks good!
