### ISSUE TITLE
Export analysis data to external database

### ISSUE THREAD

**Issue by Jocelyn0830** [privacy-tech-lab/gpc-web-crawler#23]
Currently we are using indexedDB API to store our data in the user's browser. Now we want to be able to directly output our analysis data from our extension to some external database, for instance, SQL or mySQL.

**Comment by Jocelyn0830** [comment]
A more reasonable way for us to do this is to create REST API front ends to our databases and call them from the extension.
We can look into some database options as discussed [here](https://github.com/privacy-tech-lab/gpc-web-crawler/issues/20#issuecomment-1308176658).

**Comment by Jocelyn0830** [comment]
I set up our database using google cloud mysql. I created a table to hold our analysis data. It looks like
![Screen Shot 2022-11-29 at 09 33 39](https://user-images.githubusercontent.com/102534933/204557228-6b103b0b-7db3-4af8-8dd4-0e789a2ef700.png)
I put some dummy data for later testing. I am now working on writing REST the api in our code. I am figuring out how to retrieve data from sql in our extension.

**Comment by Jocelyn0830** [comment]
In our last meeting, @SebastianZimmeck asked why I was testing on localhost given that our database is in the cloud. There are two ways we can connect to our Google Cloud MySQL database, either locally or through Google App Engine. The previous one is usually for testing and the later one is for production. I could imagine that later on we may need to use the Google App Engine when we implement Google Cloud functions or do the large-scale crawl. But for now, I think we should establish the connection to MySQL database locally when developing the REST API.

I successfully connected my Google Cloud MySQL database to node.js locally. I inserted some data manually into our databse for testing purposes. I wrote a GET API in the [rest-api](https://github.com/privacy-tech-lab/gpc-web-crawler/tree/issue-23/rest-api) folder. Running `node index.js` allows us to fetch all data from the cloud database. Data will be displayed on http://localhost:8080/analysis.

There is one issue with the REST API now. Without additional setting, an ETIMEDOUT error will occur when using the REST API. This is a node.js networking error. It indicates that  a TCP connection could not be established to our MySQL server. I found a temporary solution that we could run `gcloud sql connect <databse> --user=root` on our local terminal. It allowlists our IP for incoming connection for 5 minutes. However, we may still need to find a way that allowlists our IP "forever".  I turned off my firewall but it did not help.
It is also highly possible that the above problem only appears when we establish the connection locally. If we move to Google App Engine, this may longer be a problem. But still, it would be best if we solve this problem.

**Comment by Jocelyn0830** [comment]
Some additional things about Google Cloud:
- Everyone got a 90-day free trial and $300 in free credits. To save credits, remember to stop our Google Cloud instance. Otherwise, it will keep running and spending credits even after you close your browser.
- I think my personal free credits will be enough for us to develop the REST API and test our extension on a small scale. After completing the REST API, we may move to a lab account. I am also fine if everyone thinks we should move to our lab account right now.
- For safety purpose, I did not upload .env file to our repo. .env file contains essential authentication information of our database. I could share it in teams or our drive.

**Comment by Jocelyn0830** [comment]
Our next tasks:
- Implement POST API in our analysis extension. After analyzing an unvisited site, we should insert the analysis results in the database.
- Implement PUT API. After analyzing a visited site, if analysis results are changed, update them in the database.

**Comment by SebastianZimmeck** [comment]
Very nice, @Jocelyn0830! It is clear you are becoming an expert quickly ... :) 

> There is one issue with the REST API now. Without additional setting, an ETIMEDOUT error will occur when using the REST API. This is a node.js networking error. It indicates that a TCP connection could not be established to our MySQL server. I found a temporary solution that we could run gcloud sql connect <databse> --user=root on our local terminal. It allowlists our IP for incoming connection for 5 minutes. However, we may still need to find a way that allowlists our IP "forever". I turned off my firewall but it did not help.

@katehausladen, can you also look into this?

**Comment by katehausladen** [comment]
Yes, I can look into it.

Also, this looks like a good template for implementing post and put requests: https://github.com/restapiexample/nodejs-restapi-using-express-mysql/blob/e5433eb1a9b3f1cb5870afa33b53c0eeaf93f50f/index.js#L53

**Comment by katehausladen** [comment]
To fix the ETIMEDOUT error, you need to add your Public IP to the list of authorized networks in Cloud SQL.

1. Go to https://www.whatsmyip.org/ and copy the IP address listed.
2. Starting from the Google Cloud Welcome page for the project you will be using, navigate to SQL using the navigation menu. 
3. Select the instance you will be using.
4. Under the overview tab for the instance, find “Configuration” and click “edit configuration”
5. Under connections, find “Authorized Networks.” Click “add network” and add the IP address you copied earlier. Save your changes. 
Now, when you run node index.js, there should not be any ETIMEDOUT error.

**Comment by katehausladen** [comment]
I committed a preliminary successful implementation of POST requests (tested with postman). Since I don’t have access to Jocelyn’s database yet, I implemented it for the database I had recreated from this tutorial: https://billmartin.io/blog/how-to-build-and-deploy-a-nodejs-api-on-google-cloud (the same one Jocelyn followed). I added it to her index.js as a comment since it is not yet adapted for her database (I’m happy to adapt it once we figure out multi-user access, basically we just need to change variable/database names).

**Comment by Jocelyn0830** [comment]
I spent a lot of time looking into POST request with Express this week. It was not successful till I saw Kate's implementation of POST request with an alternative database. It turned out that I was using wrong syntax for MySQL. Kate's implementation uses the parameter `req` to ask for input from client. After looking into the `req` parameter, I figured out that we even do not need a real POST request, since we are not asking anything from the user. We just need to perform a query to insert analysis data into our MySQL database. We do not even need the .post() function. This idea works. Now the remaining step is just to convert our old data type for storing analysis data into some new data type that MySQL takes and use that as the input for query to MySQL database.

**Comment by katehausladen** [comment]
The post request is done. It sends one entry to the cloud sql db after analysis finishes on a site (requests made with axios). Updates are in the issue-23-2 branch. 

To test, you locally run the REST API (in the terminal, navigate to the rest-api folder and run node index.js), and then install the analysis extension from the issue-23-2 branch. When you load a website, analysis automatically runs (the optmeowt logo will turn yellow while it’s running). If you check http://localhost:8080/analysis, the latest entry should be the site you just visited.

**Comment by Jocelyn0830** [comment]
I updated the README with instructions on running the gpc-analysis-extension with REST api and mysql and created a pull request. We can switch to a lab google cloud mysql acoount now.

**Comment by SebastianZimmeck** [comment]
Excellent! I will set it up ...

**Comment by SebastianZimmeck** [comment]
> We can switch to a lab google cloud mysql acoount now.

@Jocelyn0830, I just need to create a [Google Cloud MySQL instance](https://cloud.google.com/sql/docs/mysql/create-instance), or is there anything else we need?

**Comment by Jocelyn0830** [comment]
Resolved
