### ISSUE TITLE
Check the Wiki for potentially sensitive info and remove such

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#34]
As discussed, @katehausladen, it would be good if you can take a detailed look at the Wiki and make sure there is no sensitive info there that is leaking publicly (API keys, database usernames, non-public connection info to our database, ...) What is OK to disclose in the technologies and Google Cloud we use and what is not? And if you come across such info, delete it.

**Comment by katehausladen** [comment]
I think everything looks good!
