### ISSUE TITLE
Add architecture diagram

### ISSUE THREAD

**Issue by katehausladen** [privacy-tech-lab/gpc-web-crawler#35]
As discussed in the meeting, we will be adding an architecture diagram to the Readme.

**Comment by katehausladen** [comment]
I made 2 versions:

The first is the version where the docker container runs locally. This is the version that we get around a 90% success rate.
![web-crawler-architecture-LD](https://user-images.githubusercontent.com/40359590/221015277-7c21d06e-6bf5-4551-97db-44c804478b71.png)


The second version is the version where the docker container has been deployed to Google Cloud. This is the version that we get around a 60% success rate.
![web-crawler-architecture-CD](https://user-images.githubusercontent.com/40359590/221015318-d834c17f-a76f-4325-9c8e-cceeb83f8427.png)


If anyone has any suggestions for modifications, let me know. I'll put the final diagram into the Readme once we decide what our exact architecture will be.

**Comment by SebastianZimmeck** [comment]
> If anyone has any suggestions for modifications, let me know. I'll put the final diagram into the Readme once we decide what our exact architecture will be.

Excellent! Also, if you could put in the source file there (PowerPoint or other document you used) for later modifications.

**Comment by katehausladen** [comment]
[web-crawler-architecture.pptx](https://github.com/privacy-tech-lab/gpc-web-crawler/files/10819304/web-crawler-architecture.pptx)

**Comment by SebastianZimmeck** [comment]
Once the local crawler is ready, we need new diagram. :)

**Comment by katehausladen** [comment]
Updated powerpoint:
[web-crawler-architecture.pptx](https://github.com/privacy-tech-lab/gpc-web-crawler/files/11183490/web-crawler-architecture.pptx)

This includes the revised architecture diagram as well as a flow chart to help visualize the flow of the crawler script. I will add these to the readme with the High level architecture description (issue #39)

**Comment by Jocelyn0830** [comment]
Resolved.
