### ISSUE TITLE
Implement put request to write site-id in output data

### ISSUE THREAD

**Issue by Jocelyn0830** [privacy-tech-lab/gpc-web-crawler#40]
As Kate and I discovered in our testing, some sites redirect to other domains. For example, fb.com redirects to facebook.com. Thus, the domain name in the output analysis data is different from the input domain name. We need to have a way to easily identify those sites that redirect and their original domain names. 

After our discussion, we plan to add a new column in the table called "site-id" which will allow us to easily identify the input domain name. The difficult part is that analysis data is posted from the analysis extension to the SQL database. It is not possible for the analysis extension to know the "site-id" since the "site-id" is in the csv file which is input to the crawler. Thus, we will first try to implement a PUT request in the crawler and see if it can update the output analysis data with the site-id.

**Comment by SebastianZimmeck** [comment]
That is a good point. It would be good to keep track of the redirect. Maybe, columns Request URL and Redirect URL or something similar. In any case, for transparency it is important that a redirect occurred.

**Comment by Jocelyn0830** [comment]
Kate and I decided to maintain two tables in our SQL database. There are a couple of reasons for this decision:
(1) As we decided to crawl using two mac minis (or our MacBooks), it will be easy for us to test if the hardware is causing issues by looking at success rate on each machine separately. 
(2) We needed to identify sites that redirect. In our testing, we found that in our SQL database, there were sites not in the input csv file. It is difficult to pair those sites with their original domain names in the csv file. To solve that, we decided to input id of a site listed in the csv file in our SQL database as an identifier. @katehausladen can explain more details of how we implemented this feature. 

We created two tables and changed our crawler, rest-api and analysis extension code. Each time we start the crawler, we will choose which table to use in the command line. Then the rest-api and analysis extension will follow our choice automatically. The script appears to work well now after brief test. We will do more testing (including on mac minis) to make sure it works.

**Comment by katehausladen** [comment]
Put request details:
For every domain loaded by the crawler, the analysis extension adds the usual analysis data plus a null entry of site_id. After that data is added to the database, local-crawler.js checks if the expected domain is in database. If it is, we update the site-id with a put request. If that domain has not been added, it checks for the last null site-id. If there is no null site-id, then no site was added to the db. If there is a null-site id, then we know that site was redirected and update that entry's site-id with a put request. In this way (in combination with using 2 tables to guarantee that there should never be more than 1 null site-id at a time), we can easily distinguish any sites that were not added or that were redirected and correlate redirected sites with the site-id from the csv.

**Comment by Jocelyn0830** [comment]
The two table approach works well. This should be resolved.
