### ISSUE TITLE
Which Google Cloud machines to use?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#43]
I received the following email from Google Cloud. It would be cheaper to use `e2-medium` instead of  `e2-standard-2`. So, can we use the former? I can also make the switch, and we see how it goes.

> Builds that use the default machine type will automatically begin to use e2-standard-2 once it becomes available during July 2023. However, pricing and free tier changes will not occur until September 1, 2023. Until September 1, 2023, you will be billed as if the machine type didn’t change. After this date, e2-medium machine types will still be available for use outside of the Free Tier at $0.003 / build-minute by specifying machineType in your cloudbuild.yaml file.

> <img width="484" alt="Screenshot 2023-05-16 at 10 24 24 AM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/11034003/bef00ae1-c899-4984-a674-14f4bcbf6804">

**Comment by Jocelyn0830** [comment]
After reviewing our setup, I think we are not currently using Google Cloud machines. It seems that this is also for the cloud crawler only, but I need to double check with Kate.

Besides, looking at the screenshot, I think it is worth discussing which one is cheaper (in case we want to use cloud crawler in the future). Although `es2-medium` seems to be cheaper, the free tier is only 120 build-minute/day. It is impossible to complete crawl in 2 hours. That says, we will be charged each time we crawl. For `e2-standard-2`, the free tier is 2500 build-minute/month, about 42 hours/month. Assuming each crawl takes 5 hours to complete, it seems that we will be able to do 8 crawls for free.

**Comment by SebastianZimmeck** [comment]
> After reviewing our setup, I think we are not currently using Google Cloud machines. It seems that this is also for the cloud crawler only, but I need to double check with Kate.

Thanks, @Jocelyn0830! From your perspective, can I go ahead and disable/delete the Google Cloud machines? If there is anything to preserve in the Cloud machines (code, ...), please preserve it beforehand.

If we need them in the future, we can create new ones. At the moment, it does not like we would be needing them as we crawl locally and only use Google Cloud for the database.

@katehausladen, if you have any additional information, please chime in.

**Comment by Jocelyn0830** [comment]
> > After reviewing our setup, I think we are not currently using Google Cloud machines. It seems that this is also for the cloud crawler only, but I need to double check with Kate.
> 
> Thanks, @Jocelyn0830! From your perspective, can I go ahead and disable/delete the Google Cloud machines? If there is anything to preserve in the Cloud machines (code, ...), please preserve it beforehand.
> 
> If we need them in the future, we can create new ones. At the moment, it does not like we would be needing them as we crawl locally and only use Google Cloud for the database.
> 
> @katehausladen, if you have any additional information, please chime in.

@SebastianZimmeck I agree that we can disable the Google Cloud machines. We have documented everything we need to set up the cloud crawler in the wiki. If we ever need it again, we can always go back to the previous commits/wiki. I will also wait for Kate's opinions.

**Comment by Jocelyn0830** [comment]
Kate and I discussed whether disabling the Google Cloud machines influences the use of rest api since it is deployed in Google Cloud. We will check and make sure.

**Comment by Jocelyn0830** [comment]
> Kate and I discussed whether disabling the Google Cloud machines influences the use of rest api since it is deployed in Google Cloud. We will check and make sure.

For rest api, we are using Google Cloud Run, not Google Cloud machines. I believe the two services are independent, so we can disable Google Cloud machines.

**Comment by SebastianZimmeck** [comment]
We decided on a local setup, and this issue is moot.
