### ISSUE TITLE
Upgrade Google Cloud Container Registry to Artifact Registry?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#44]
I received the following email from Google. Are we even using the Container Registry or is that a leftover from our crawler? @Jocelyn0830, can you look into this? 

> [Action Required] Upgrade to Artifact Registry from Container Registry before May 15, 2024

> Container Registry will be phased out, starting May 15, 2024. Please review the options below for how to upgrade your projects to Artifact Registry.

> We’re writing to let you know that Container Registry will be phased out starting May 15, 2024, and replaced by Artifact Registry, which offers a variety of [new capabilities](https://notifications.google.com/g/p/ACUgQrG8C8l0KI0VqFLKj0SR1P1JNfwWugz5b9WfycIWVjQsR5WB48GNPam2FO0URT-OHBGyYXENhhvVhifTRVQnPmNS6xPjbMqpIYU1bZ6Iq5ltXLlLot_Vg8UCiLurx-AIpvZ3wThHlsMPhu_AT2FjvQo3Ekta3dWP2dq6qnJV55uKx6QMnijcS0cfpK_jWmYbgxbc8eG_bv3Ei2xzCS0sUV3cILzvTluCHxsNqSk3tMUham0nv-pw_H5yCjS5QGOmUbkFec5dqkARo7QjBH-AuiY).

> What do you need to know?
Starting May 15, 2024, we’ll limit the projects allowed to host images in Container Registry. The only projects allowed to host the images will be the ones in which:

> 1) The Container Registry API was enabled before May 15, 2024.
> 2) Images were pushed to Container Registry.
For all other projects, once the discontinuation starts, images will be automatically hosted in [Artifact Registry](https://notifications.google.com/g/p/ACUgQrG_O0mezgAaMrTbrxN0viMtb1ZRphOsygWzSXke-xiLjb5qUMV5smjQJfmQXa7oqE_611Nydz7__xPPh0yujglbLrhpTICwUa1G7TFlirFbfXA7LL0esb8_fg6y-lYw4koCGrevwIChBK5MWu0iYuECcUWi0FSQmivZr0TMV9LuTAj21n2W3cBmJA5CP7Jw3cJQfZ3vl6ypjthbOKE), and you will no longer have the option to host images in Container Registry. Container Registry is in maintenance and only receives critical legal or security fixes.

> Once you’ve transitioned to Artifact Registry you’ll be able to store images in:

> - [Standard Artifact Registry repositories](https://notifications.google.com/g/p/ACUgQrHHW4AWwZ7Q1NCzDKXvtLHglJ9rtDWH_KvgCvRCPoIB2YQrJ0Q4v924QMngjyCvVJDiwk7VYVS_4IckP4BtFZUCvEKBElu0XbDRZ_PPLZ6dWT21QL7lr2sWFAeKd2FwI9hS-boCLctSB2tJMr5PZuY7WV6rMc5KOHIU1vze8HukpFmnxj8qBt-aYwqdQhSrR2KmOG9OWX9zzO9FIuarhyQEhXEJl0fKipYz_2jFSrTndsCz) on the pkg.dev domain in any supported region. This option can reduce latency and egress costs to Google Cloud runtime environments like GKE.
> - [Repositories with gcr.io domain support](https://notifications.google.com/g/p/ACUgQrF_gAMU5ERnRFt0pS6BI2BJy6ieM4zGPi9gATjv-O_MJBTqzfqUzvDaNvrzWBDyVA8ol7ikzK0jcrjiqsV2wBLyuSPkmpZX2v3eQ1vy5bnym7j__WQev4RoW_PBsP-29NcJ8K0qUXP4QcoMbVtUWOVgdfrvSme_DwFb0nN2kt6mnIukcBC52Mt5LJVcs9KG3HcHTBE-VU0O6mkIjLCmoqrpxX38dP5M50J8PzV2KtyfT_RzRONvAg) for backwards compatibility with your existing automation. These repositories are only available in the same multi-regions that Container Registry supports.
Artifact Registry pricing model is not based on the underlying storage and egress costs in Cloud Storage like Container Registry. Storage costs are higher in Artifact Registry, but it provides better options to manage egress costs. For details about how this new pricing might impact your projects and options for managing costs, see our [pricing documentation](https://notifications.google.com/g/p/ACUgQrEPfuD2i6qSSHybL9HTkWc3x-1uzjyYRLv_ucdZG95z9Px6pFEH7zm1l8uiUJq96jm5QpI_TRKhvdHDXv1wJ4_Y0haai29IMrwWxHjkUTWgyEqGYK8oXvavUhflGRHLtJ31gKAQc4rxftpBTb5n-O4k_ZnVuryszT3uy8ZwJRxuH5L4-Ku0P7Z3MhzZk7A6v8ueQYXlFtZSZvl1HrA5V0Q).

> Note that if you use Container Registry through a dependent service such as Cloud Build, you will be billed for Artifact Registry instead of Container Registry within new projects after May 15, 2024. Requests will also use Artifact Registry quota instead of Container Registry quota. See our [documentation for Artifact Registry quota limits](https://notifications.google.com/g/p/ACUgQrFd62OBb1wPCYujRTxSCQiagzqKFDBRSuZUgwR5iVhM0BWA-kcI92G6V-WIKoxUrMeHV7-hVRChg7MnOFfCyrczJ0o3BPguHrUJ0O6tGBcvvKs3K0eezv_VUQiYcbcrSpCNln-NgNcbsQ5qKmeuUohGL8us8sMG1bpRUpNliV_F3iY6V7hFI7j0TVXXmWYPE0i1zgM3hzFAOfpKZi99zw).

> What do you need to do?
These are the two transition paths we recommend you follow depending on your project’s architecture:

> For projects where you use Container Registry:
Consider moving to Artifact Registry. Learn about [options to transition to Artifact Registry](https://notifications.google.com/g/p/ACUgQrFy-PNDeg6UDu1UW9PXclmRAhIO07lZIfK4yYF0FmQxF00ULEpxQjJNoR9bxhQkmRyux762uifQ6iST9TSwrnY7gPVTJz6N9KWoO3oK2W23u8-5kTtpbnpscXjc6XctF3Aprq6Ty9u14J2HUS6PaJiKBbGzM79UR2DPksmckJ9F6QCJLlf6Gd1aOY3JWhFVum4uozQ1bqBLgE0x3K0FENF0glOOK988zTbhOzpG-5LomeqlnxwpDdGbZQqC) to prepare for discontinuation of Container Registry.

> For projects where you are not currently using Container Registry:
Prepare for automatic hosting of gcr.io in Artifact Registry before May 15, 2024:

> Change any automation or workflows to enable the Artifact Registry API instead of the Container Registry API
Grant Artifact Registry roles to users and service accounts that interact with Container Registry.
Update automation that configures storage buckets for Container Registry to perform equivalent actions on Artifact Registry repositories.
Test [gcr.io hosted in Artifact Registry](https://notifications.google.com/g/p/ACUgQrF_gAMU5ERnRFt0pS6BI2BJy6ieM4zGPi9gATjv-O_MJBTqzfqUzvDaNvrzWBDyVA8ol7ikzK0jcrjiqsV2wBLyuSPkmpZX2v3eQ1vy5bnym7j__WQev4RoW_PBsP-29NcJ8K0qUXP4QcoMbVtUWOVgdfrvSme_DwFb0nN2kt6mnIukcBC52Mt5LJVcs9KG3HcHTBE-VU0O6mkIjLCmoqrpxX38dP5M50J8PzV2KtyfT_RzRONvAg) using a test project, or transition a project where you are currently using Container Registry.
If you don’t take any of these transition paths, your existing automation workflows for Container Registry might not work in new projects after May 15, 2024.

> We’ll send additional communications about future phases, how it will impact your existing Container Registry usage, and any required actions.

> Your projects that use Container Registry currently are listed below:

> gpc-crawler

> We’re here to help
For further instructions to prepare new projects, see our guide to [prepare for gcr.io hosted on Artifact Registry](https://notifications.google.com/g/p/ACUgQrF9-nk5OS2DZWHhfb1mO9S-tVT33IVRlKVIyMDW9_5NrxgLWB4Uvqs6lVRRUeFtLgArY_2r20MQEZcynp5dFOznvhdJK5uZG4HBeiBgNIMCzazHCXOHwMrxENooO5HWAQBHjW2-UrUXUZWFM1FiYUNiuogAEUanDRREkS5cRLZ7ipCbk_G4vTNUWBJf0DKymKu761kZWaqHtD7sss2prdV4vZ0qOaq9XPzolBZLjxEsMp4).
Additional details about this transition will also be published in our [release notes](https://notifications.google.com/g/p/ACUgQrF8XGvZEcRc_5syV7VTCpSTGM3ZTSIJUEeIkt3kKgjshl9T-qbS2Qk1Hmv2IAlcV_z5tkNEtQkhmHZv8_2BgsK5iZVIlVXCxuR3O87QLHiAHozIctsHZmw0nw4iEE3uef5K2HNN8pBCBgIth8vZ_Ib6T_GQN0QKOcNEjQjzPrVhMVV3zzzPE1rAcQViaGRYYUgdtPrwdclkdTUKp5j_YWFdj5kZpRpkDNMw_QY) page.
We thank you for your patience and understanding as we make this important change.

**Comment by Jocelyn0830** [comment]
After reviewing our setup, I believe the Google Cloud Container Registry is only used in our cloud crawler. It seems to be complicated to move our images from Google Cloud Container Registry to Artifact Registry. I am not sure if it worths the time and money (there will be a cost) since we decide not to use our cloud crawler. Also given that Google Cloud Container Registry will be kept till next year, we still have a year to decide if we want to continue working with the cloud crawler. I am happy to hear what others think @SebastianZimmeck and @katehausladen

**Comment by SebastianZimmeck** [comment]
Thanks, @Jocelyn0830! My comment is the same as [here](https://github.com/privacy-tech-lab/gpc-web-crawler/issues/43#issuecomment-1555021044). So, I would go ahead and remove the Google Cloud Container Registry. As our free credits have run out, I do not see much of reason to keep them around (though, please feel free to let me know otherwise, @Jocelyn0830 and @katehausladen).

**Comment by Jocelyn0830** [comment]
Resolved
