### ISSUE TITLE
Update readme and architecture diagram

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#49]
As we are now doing a local crawl, the documentation needs updating accordingly.

**Comment by katehausladen** [comment]
Updated powerpoint with architecture diagram:
[web-crawler-architecture.pptx](https://github.com/privacy-tech-lab/gpc-web-crawler/files/11777787/web-crawler-architecture.pptx)

**Comment by katehausladen** [comment]
The readme and wiki are both updated to reflect the local setup.
