### ISSUE TITLE
Identify sites that go to "Access Denied" or "Verify you are a human" pages when loaded

### ISSUE THREAD

**Issue by katehausladen** [privacy-tech-lab/gpc-web-crawler#51]
I've noticed that there are some sites that go to a page that says some iteration of "Access Denied" or "Verify you are a human." I think this is mostly caused by the VPN (i.e. the VPN IP address is blocked/recognized), but the crawler probably contributes, too. It seems like there is some variability in the sites run to run, particularly in the "Verify you are a human" category.
We want to: 
1. identify these sites, since the crawl data will be inaccurate
2. hopefully find a way to bypass at least some of these issues

Currently, I am identifying them by the title of the site (i.e. "Access Denied" and "Just a moment..." in the pictures below).

<img width="525" alt="Screenshot 2023-06-21 at 10 51 52 AM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/72fd62c8-3977-43d9-832a-a67930a7be68">
<img width="525" alt="Screenshot 2023-06-21 at 10 52 36 AM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/5fa3ab0d-287f-4068-8ad3-ffa6574589ba">

The sites I do identify are logged as either a "VerifyHumanError" or a "AccessDeniedError". The crawler won't restart after these errors, so it doesn't affect the overall flow.
In the latest full crawl, the sites that asked to verify you were a human were:
 VerifyHumanError: [
    'https://www.legacy.com',
    'https://www.ticketsatwork.com',
    'https://www.fixya.com',
    'https://www.cameo.com',
    'https://www.cardinalcommerce.com',
    'https://www.cinemark.com',
    'https://www.securecafe.com',
    'https://www.lordandtaylor.com',
    'https://www.moneytalksnews.com',
    'https://www.allegiantair.com',
    'https://www.newspapers.com',
    'https://www.rentcafe.com',
    'https://www.babylonbee.com',
    'https://www.fleetfarm.com',
    'https://www.jegs.com',
    'https://www.appurse.com',
    'https://www.123-movies.com',
    'https://www.camelcamelcamel.com',
    'https://www.muscleandstrength.com']
And the sites with Access Denied were:
  AccessDeniedError: [
    'https://www.sprint.com',
    'https://www.kroger.com',
    'https://www.petsmart.com',
    'https://www.tacobell.com',
    'https://www.subway.com',
    'https://www.zoosk.com',
    'https://www.officedepot.com',
    'https://www.hotwire.com',
    'https://www.meijer.com',
    'https://www.jcrew.com',
    'https://www.backcountry.com',
    'https://www.littlecaesars.com',
    'https://www.fisglobal.com',
    'https://www.fossil.com',
    'https://www.flyertalk.com',
    'https://www.citizensbank.com',
    'https://www.earthlink.net',
    'https://www.apartmentfinder.com',
    'https://www.demandforce.com',
    'https://www.pizzahut.com',
    'https://www.t-mobile.com']

**Comment by katehausladen** [comment]
some more examples:

<img width="550" alt="ask" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/590fe373-c28e-47ca-ae30-b8ba1e2ce330">
<img width="550" alt="petco" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/7583f75b-dfa8-4eab-8f0a-125d9e9e15f3">
<img width="550" alt="zoominfo" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/c04e24e0-f1de-4efa-b927-23cbb3ac8994">

**Comment by katehausladen** [comment]
I wrote some code to click the "Verify you are a human" button by Cloudfare (as in the cinemark.com example). When the button is clicked, the same captcha page loads again. So since clicking the button alone does not work, Cloudfare is definitely detecting that we are using Selenium. I haven't found any packages that would help with this for Selenium with Nodejs and Firefox, and since it's only impacting ~20 sites, I'm not sure it's worth spending a ton of time trying to bypass. We can discuss this more at the meeting.

**Comment by SebastianZimmeck** [comment]
> The crawler won't restart after these errors, so it doesn't affect the overall flow.

The crawler continues crawling (as a clarification).

> impacting ~20 sites

For the total about 1,800 sites, though, the 20 are specifically for the Cloudfare human-checks.

**Comment by katehausladen** [comment]
We decided in the last meeting that we will not try to bypass any human checks. We will add new titles to the regex in the visit_site function in local-crawler.js as we see more sites like this. The readme is also updated to include this in section 4.
