### ISSUE TITLE
Add OptanonConsent columns

### ISSUE THREAD

**Issue by katehausladen** [privacy-tech-lab/gpc-web-crawler#61]
As discussed in our meeting, I am adding columns for the isGpcEnabled string in One-Trust's OptanonConsent cookie before and after GPC is sent.

**Comment by katehausladen** [comment]
I added the columns. The new command to make the database is 
```console 
CREATE TABLE entries (id INTEGER PRIMARY KEY AUTO_INCREMENT, site_id INTEGER, domain varchar(255), dns_link BOOLEAN, sent_gpc BOOLEAN, uspapi_before_gpc varchar(255), uspapi_after_gpc varchar(255), usp_cookies_before_gpc varchar(255), usp_cookies_after_gpc varchar(255), OptanonConsent_before_gpc varchar(800), OptanonConsent_after_gpc varchar(800));
```
The potential values for these columns are: 

- null (if the OptanonConsent cookie doesn't exist)
- isGpcEnabled=1 (if GPC is on according to the cookie's value)
- isGpcEnabled-0 (if GPC is off according to the cookie's value)
- no_gpc (if the cookie is found, but there is no isGpcEnabled string in the cookie's value)

**Comment by SebastianZimmeck** [comment]
Thanks, @katehausladen. Do we need to update the Wiki accordingly?

**Comment by katehausladen** [comment]
Yes, I'll get to that tomorrow.

**Comment by katehausladen** [comment]
[web-crawler-architecture.pptx](https://github.com/privacy-tech-lab/gpc-web-crawler/files/12176085/web-crawler-architecture.pptx)
updated architecture powerpoint
