### ISSUE TITLE
Does Google's Topics API have a consent flag that we can use similar to the US Privacy String/USPAPI?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#63]
As Google has begun to roll out the [Topics API](https://developer.chrome.com/en/docs/privacy-sandbox/topics/overview/) as a replacement for third party cookie tracking, is there a flag in the Topics API similar to the US Privacy String/USPAPI? 

<img width="555" alt="Screenshot 2023-08-02 at 3 30 37 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/11034003/f7a16ace-f9eb-4b7b-8a4b-50f845933a0e">

For example, in the above picture there is an API call and it shows a GDPR consent flag (albeit, with the value encrypted or serialized). So, that begs the above question. If there is such a flag in the Topics API, could we leverage it in lieu of the US Privacy String/USPAPI? 

Is Google possibly using the [Restricted Data Processing (RDP) flag](https://support.google.com/google-ads/answer/9614122?hl=en) in the context of the Topics API?

@OliverWang13 will take the lead on this with @katehausladen helping.

**Comment by OliverWang13** [comment]
To clarify, is this reporting a call being made by Criteo to the user (possibly, on the site www.fernsehserien.de)

That is to say, it is not what the Topics API returns when called.

**Comment by OliverWang13** [comment]
dmarti, who I believe you are connected to as well, is quite active on the github. In [this issue](https://github.com/patcg-individual-drafts/topics/issues/31), there is a reference to some opt out language in the readme. It says:

"If the user opts out of the Topics API, or is in incognito mode, or the user has cleared all of their history, the list of topics returned will be empty"

"The Topics API will have a user opt-out mechanism"

However, I believe these indicate that the user can opt out of the topics API, but they will likely not have a tool for opting out of all sales in general.

**Comment by Jocelyn0830** [comment]
I agree with @OliverWang13 that they will likely not have a tool for opting out of all sales. And I didn't find in their github/documents anything related to consent flag. In their github there are couple issues talking about if topics api should be considered as a "sale" of personal information but the developer refused to directly answer the question.

[this issue](https://github.com/patcg-individual-drafts/topics/issues/25) here points out that it is possible to develop an extension that removes a topic from local topic information store. It seems to me that we can have an extension that checks if the website obeys the law and removes/blacklists those topics. But this should be something we think of a while ago.

Something I plan to do next: I will see if I can try using topics api myself. It may be useful to look at what it returns and check the network tab of the browser inspection tool.

**Comment by SebastianZimmeck** [comment]
> Something I plan to do next: I will see if I can try using topics api myself.

Sounds good! It seems that there is nothing concretely for us to do here. But before we move on, it would be good, indeed, if you can get a basic understanding of the Topics API, @Jocelyn0830. Especially, how does a website request the topics? And are there any settings a website can make, e.g.,  more privacy-preserving topic serving or something similar? Maybe, spend a week or so on this, @Jocelyn0830.

**Comment by SebastianZimmeck** [comment]
> Does Google's Topics API have a consent flag that we can use similar to the US Privacy String/USPAPI?

The answer is "No."

**Comment by SebastianZimmeck** [comment]
One side point:

Is Google Topics API selling, sharing, targeting per state privacy laws? So, if people enable GPC, would that require turning off the Topics API? It is not an immediately relevant question for us, but would need to be answered eventually. I do not think anybody looked into that.

**Comment by Jocelyn0830** [comment]
> With the Topics API, the browser observes and records topics that appear to be of interest to the user, based on their browsing activity. This information is recorded on the user's device. The Topics API can then give API callers (such as ad tech platforms) access to a user's topics of interest, but without revealing additional information about the user's browsing activity.

It seems that after calling the Topics API, a website can get the topics directly. (Personally I think that is what Topics API is for)

More in detail,
> An API caller is said to have observed a topic for a user if it has called the document.browsingTopics() method in code included on a site that the Topics API has mapped to that topic.

**Comment by Jocelyn0830** [comment]
Also I didn't find explicitly more privacy preserving settings that websites can make. Based on my understanding, the websites can only get zero to three random topics. As I read in Topics API's document, they claim that their mechanism has reduced fingerprinting which helps ensure that it is difficult to re-identify significant numbers of users across sites using the Topics API alone.
