### ISSUE TITLE
Update readme and other documentation once we settle on new methodologies

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#65]
Especially, once #59 and #60 are done.

**Comment by katehausladen** [comment]
The readme + wiki have been updated to reflect the changes from issue #60.

updated architure/flow chart ppt: [web-crawler-architecture.pptx](https://github.com/privacy-tech-lab/gpc-web-crawler/files/12873544/web-crawler-architecture.pptx)

**Comment by katehausladen** [comment]
The readme + wiki have been updated to reflect the changes from issue https://github.com/privacy-tech-lab/gpc-web-crawler/issues/59.
updated architure/flow chart ppt: [web-crawler-architecture.pptx](https://github.com/privacy-tech-lab/gpc-web-crawler/files/13492251/web-crawler-architecture.pptx)
