### ISSUE TITLE
Fix setup error and change readme as necessary

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#81]
@Mattm27 encountered a setup issue:

> I have been in contact with Kate about this error I am receiving when connecting to the REST API for the web crawler, but we are having a tough time pinpointing exactly why it is occurring. Seems like it is some sort of privilege issue, and I was wondering if you had any other ideas on how to fix it. Here is a screenshot of the error: 

<img width="1023" alt="Screenshot 2024-01-10 at 2 02 21 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/11034003/45ced1d6-d0f6-4bcb-a59b-655b0a0ea323">

If this is a general setup issue and/or the readme is incorrect or insufficient, we should add a fix.

**Comment by Mattm27** [comment]
Issue resolved, updating ReadMe.
