### ISSUE TITLE
Understand how to run web crawl analysis scripts

### ISSUE THREAD

**Issue by Mattm27** [privacy-tech-lab/gpc-web-crawler#88]
As discussed in the meeting today, it would be helpful if lab members could get comfortable entering the data from a crawl into Google Colab for analysis ahead of the next planned crawl in early April.

**Comment by katehausladen** [comment]
I added some details on saving the data and using the colab in [the wiki](https://github.com/privacy-tech-lab/gpc-web-crawler/wiki/For-lab-members-performing-crawls:). The colab pulls data directly from the drive, so as long as all of the data is saved/uploaded to the drive in the correct way, the colab should run.

**Comment by katehausladen** [comment]
We'll revisit this in April when we crawl again
